// Generated by Wrangler
// After adding bindings to wrangler.jsonc, run `npm run generate-types` or `npx wrangler types` to update this file
interface Env {
	SESSION: KVNamespace;
	IMAGES: any;
	AI: any;
}
